### ISSUE TITLE
Cannot start psql

### ISSUE THREAD

**Issue by dzmitrys-dev** [ohardy/dokku-psql#9]
$ dokku psql:start
-----> Starting Postgresql server
e29753546c89263274ce607cf6ebfefbd3c0ccd8d1ee0e96c4777dcfee4a1582
Error response from daemon: Cannot start container e29753546c89263274ce607cf6ebfefbd3c0ccd8d1ee0e96c4777dcfee4a1582: Error starting userland proxy: listen tcp 127.0.0.1:5432: bind: address already in use
-----> Restarting applications

**Comment by cadicallegari** [comment]
It happens to me when a instance of postgresql service is running at my host machine.

Check if service are running at host with that command:

> service postgresql status

If the command return online, stops the service with that command:

> service postgresql stop

and try to start psql again:

> dokku psql:start
